apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging_app
  template:
    metadata:
      labels:
        app: messaging_app
    spec:
      containers:
        - name: messaging_app
          image: geecodez/messaging_app:latest
          imagePullPolicy: IfNOtPresent
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              value: "your_db_name"
            - name: MYSQL_USER
              value: "your_db_user"
            - name: MYSQL_PASSWORD
              value: "your_db_password"
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_PORT
              value: "3306"

apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  type: ClusterIP
  selector:
    app: messaging_app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000