apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-ingress
  annnotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
      - host: messaging.local
        http:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: messaging-app-service
                port:
                  number: 8000
